In [5]:
puzzle_1 = [
[8, 2, 4, 7, 9, 5, 1, 0, 3],
[3, 5, 1, 0, 6, 4, 8, 7, 0],
[7, 9, 0, 8, 0, 3, 0, 0, 2],
[5, 7, 8, 4, 2, 1, 9, 3, 0],
[9, 0, 0, 5, 0, 8, 2, 1, 4],
[0, 0, 2, 6, 0, 9, 7, 8, 5],
[0, 4, 9, 3, 0, 7, 6, 0, 8],
[0, 0, 0, 9, 8, 2, 4, 0, 0],
[2, 8, 5, 1, 4, 0, 3, 0, 7]
]

puzzle_2 = [
[1, 9, 3, 7, 0, 8, 0, 5, 0],
[5, 4, 0, 0, 1, 9, 0, 0, 7],
[7, 2, 8, 0, 4, 6, 9, 3, 1],
[8, 7, 0, 0, 3, 5, 1, 0, 6],
[0, 6, 5, 0, 0, 1, 7, 4, 3],
[9, 3, 1, 6, 0, 4, 5, 0, 2],
[0, 8, 0, 1, 0, 0, 0, 7, 5],
[3, 1, 2, 9, 5, 7, 0, 6, 8],
[6, 5, 7, 4, 0, 3, 0, 1, 9]
]

puzzle_3 = [
[5, 1, 7, 8, 4, 3, 2, 0, 6],
[9, 6, 4, 5, 7, 2, 1, 8, 0],
[0, 0, 8, 1, 6, 9, 4, 5, 7],
[0, 0, 0, 0, 0, 5, 6, 1, 0],
[4, 0, 0, 6, 2, 1, 9, 0, 8],
[1, 9, 0, 4, 8, 7, 3, 0, 0],
[0, 8, 1, 3, 0, 4, 7, 6, 9],
[6, 3, 9, 7, 0, 8, 0, 4, 2],
[0, 4, 5, 0, 9, 6, 8, 0, 1]
]

puzzle_4 = [
[0, 0, 0, 8, 0, 6, 0, 0, 0],
[0, 5, 0, 3, 0, 0, 7, 9, 2],
[4, 0, 7, 0, 0, 0, 0, 0, 3],
[3, 0, 0, 0, 5, 8, 9, 0, 4],
[0, 9, 0, 0, 3, 7, 1, 2, 0],
[5, 6, 0, 2, 0, 9, 0, 0, 8],
[1, 0, 9, 0, 0, 2, 4, 0, 0],
[0, 0, 5, 0, 9, 3, 0, 1, 0],
[7, 0, 6, 4, 8, 0, 2, 0, 0]
]

puzzle_5 = [
[4, 0, 2, 0, 6, 3, 0, 7, 1],
[9, 3, 1, 0, 0, 7, 6, 0, 0],
[6, 0, 8, 9, 0, 0, 3, 0, 5],
[0, 8, 0, 2, 0, 0, 4, 6, 0],
[3, 0, 0, 0, 0, 0, 8, 0, 2],
[2, 4, 6, 3, 0, 0, 0, 0, 0],
[7, 9, 0, 0, 0, 0, 0, 0, 8],
[1, 6, 0, 7, 0, 0, 2, 4, 9],
[0, 0, 0, 0, 3, 9, 7, 0, 0]
]

puzzle_6 = [
[0, 4, 5, 7, 8, 2, 1, 3, 6],
[0, 2, 0, 6, 3, 5, 8, 0, 0],
[0, 8, 3, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 5, 0, 0],
[0, 7, 6, 0, 0, 0, 4, 0, 0],
[0, 1, 0, 2, 0, 8, 0, 6, 3],
[0, 5, 1, 8, 0, 6, 7, 0, 4],
[0, 9, 0, 3, 4, 0, 0, 5, 0],
[0, 6, 8, 0, 0, 0, 0, 9, 1]
]

puzzle_7 = [
[4, 0, 0, 0, 0, 0, 0, 0, 2],
[8, 0, 0, 0, 2, 0, 0, 0, 0],
[1, 0, 2, 8, 9, 0, 0, 4, 0],
[0, 2, 0, 5, 0, 0, 0, 6, 3],
[5, 0, 7, 1, 6, 0, 2, 0, 0],
[0, 0, 0, 2, 4, 0, 7, 1, 0],
[0, 1, 8, 0, 3, 0, 9, 0, 0],
[0, 0, 0, 0, 0, 2, 8, 5, 0],
[7, 6, 0, 0, 0, 0, 3, 2, 4]
]

puzzle_8 = [
[6, 8, 3, 2, 5, 0, 9, 0, 0],
[1, 0, 0, 0, 3, 0, 6, 0, 0],
[0, 0, 0, 0, 4, 0, 0, 0, 0],
[0, 9, 0, 8, 0, 0, 0, 0, 7],
[0, 6, 1, 0, 0, 2, 5, 0, 0],
[0, 0, 7, 5, 9, 0, 1, 0, 2],
[0, 4, 0, 0, 6, 0, 0, 0, 1],
[2, 0, 9, 7, 0, 0, 0, 0, 0],
[0, 5, 0, 0, 2, 0, 8, 7, 9]
]

puzzle_9 = [
[0, 4, 0, 0, 0, 0, 0, 0, 0],
[6, 9, 0, 0, 0, 8, 1, 0, 0],
[1, 0, 0, 0, 0, 2, 4, 5, 0],
[7, 1, 9, 0, 0, 6, 0, 0, 0],
[4, 0, 0, 1, 0, 5, 0, 9, 7],
[0, 0, 3, 9, 0, 0, 0, 0, 8],
[3, 0, 0, 8, 0, 4, 0, 2, 0],
[0, 0, 2, 0, 0, 1, 8, 0, 4],
[0, 6, 0, 5, 0, 9, 0, 7, 0]
]


In [6]:
MRV_ENABLED = True
class action:
    def __init__(self, input_row, input_column, input_val):
        self.row = input_row
        self.col = input_column
        self.val = input_val

class state:
    def __init__(self, input_board=None):
        if input_board is not None:
            self.board = input_board
        else:
            self.board = []
            for rr in range(9):
                row_list = []
                for cc in range(9):
                    row_list.append(0)
                self.board.append(row_list)
        self.row_candidates = []
        for i in range(9):
            row_cand = []
            for j in range(9):
                row_cand.append(True)
            self.row_candidates.append(row_cand)
        self.col_candidates = []
        for i in range(9):
            col_cand = []
            for j in range(9):
                col_cand.append(True)
            self.col_candidates.append(col_cand)
        self.box_candidates = []
        for i in range(9):
            box_cand = []
            for j in range(9):
                box_cand.append(True)
            self.box_candidates.append(box_cand)
        self.candidate_init()

    def candidate_init(self):
        for rr in range(9):
            for cc in range(9):
                val = self.board[rr][cc]
                if val != 0:
                    self.number_select(rr, cc, val, True)

    def box_i(self, row, col):
        return (row // 3)*3 + (col // 3)

    def number_select(self, row, col, val, initialize=False):
        self.board[row][col] = val
        i = val - 1
        self.row_candidates[row][i] = False
        self.col_candidates[col][i] = False
        box_i = self.box_i(row, col)
        self.box_candidates[box_i][i] = False

    def number_correction(self, row, col, val):
        self.board[row][col] = 0
        i = val - 1
        self.row_candidates[row][i] = True
        self.col_candidates[col][i] = True
        box_i = self.box_i(row, col)
        self.box_candidates[box_i][i] = True

    def constrain_check(self, act):
        if self.board[act.row][act.col] != 0:
            return False
        i = act.val - 1
        box_i = self.box_i(act.row, act.col)
        return (self.row_candidates[act.row][i] and 
                self.col_candidates[act.col][i] and 
                self.box_candidates[box_i][i])

    def apply_action(self, act):
        self.number_select(act.row, act.col, act.val)

    def revert_action(self, act):
        self.number_correction(act.row, act.col, act.val)

    def find_possible_values(self, rr, cc):
        if self.board[rr][cc] != 0:
            return []
        res = []
        for val in range(1,10):
            i = val - 1
            box_i = self.box_i(rr, cc)
            if (self.row_candidates[rr][i] and
                self.col_candidates[cc][i] and
                self.box_candidates[box_i][i]):
                res.append(val)
        return res

def find_empty_cell(s):
    if not MRV_ENABLED:
        for rr in range(9):
            for cc in range(9):
                if s.board[rr][cc] == 0:
                    return rr, cc
        return None
    else:
        min_candidates = 10
        candidates_cells = []
        for rr in range(9):
            for cc in range(9):
                if s.board[rr][cc] == 0:
                    cands = s.find_possible_values(rr, cc)
                    count = len(cands)
                    if count < min_candidates:
                        min_candidates = count
                        candidates_cells = [(rr, cc)]
                    elif count == min_candidates:
                        candidates_cells.append((rr, cc))
        if candidates_cells:
            return candidates_cells[0]
        return None

def solve_sudoku(s, step_count=0):
    empty_cell = find_empty_cell(s)
    if empty_cell is None:
        return True, step_count
    r, c = empty_cell
    candidates = s.find_possible_values(r, c)
    for val in candidates:
        act = action(r, c, val)
        if s.constrain_check(act):
            s.apply_action(act)
            solved, final_step_count = solve_sudoku(s, step_count+1)
            if solved:
                return True, final_step_count
            s.revert_action(act)
    return False, step_count


In [8]:
import copy

MRV_ENABLED = False
step_counts_mrv_disabled = {}
for p_idx in range(1, 10):
    original_puzzle = globals()[f"puzzle_{p_idx}"]
    puzzle_copy = copy.deepcopy(original_puzzle)
    s = state(input_board=puzzle_copy)
    print(f"\n[MRV_DISABLED] Puzzle {p_idx}")
    solved, final_steps = solve_sudoku(s)
    if solved:
        print("Solution:")
        for row_data in s.board:
            print(row_data)
        step_counts_mrv_disabled[p_idx] = final_steps
        print("Step Count:", final_steps)
    else:
        print("No solution found.")
        step_counts_mrv_disabled[p_idx] = None



[MRV_DISABLED] Puzzle 1
Solution:
[8, 2, 4, 7, 9, 5, 1, 6, 3]
[3, 5, 1, 2, 6, 4, 8, 7, 9]
[7, 9, 6, 8, 1, 3, 5, 4, 2]
[5, 7, 8, 4, 2, 1, 9, 3, 6]
[9, 6, 3, 5, 7, 8, 2, 1, 4]
[4, 1, 2, 6, 3, 9, 7, 8, 5]
[1, 4, 9, 3, 5, 7, 6, 2, 8]
[6, 3, 7, 9, 8, 2, 4, 5, 1]
[2, 8, 5, 1, 4, 6, 3, 9, 7]
Step Count: 24

[MRV_DISABLED] Puzzle 2
Solution:
[1, 9, 3, 7, 2, 8, 6, 5, 4]
[5, 4, 6, 3, 1, 9, 8, 2, 7]
[7, 2, 8, 5, 4, 6, 9, 3, 1]
[8, 7, 4, 2, 3, 5, 1, 9, 6]
[2, 6, 5, 8, 9, 1, 7, 4, 3]
[9, 3, 1, 6, 7, 4, 5, 8, 2]
[4, 8, 9, 1, 6, 2, 3, 7, 5]
[3, 1, 2, 9, 5, 7, 4, 6, 8]
[6, 5, 7, 4, 8, 3, 2, 1, 9]
Step Count: 24

[MRV_DISABLED] Puzzle 3
Solution:
[5, 1, 7, 8, 4, 3, 2, 9, 6]
[9, 6, 4, 5, 7, 2, 1, 8, 3]
[3, 2, 8, 1, 6, 9, 4, 5, 7]
[8, 7, 2, 9, 3, 5, 6, 1, 4]
[4, 5, 3, 6, 2, 1, 9, 7, 8]
[1, 9, 6, 4, 8, 7, 3, 2, 5]
[2, 8, 1, 3, 5, 4, 7, 6, 9]
[6, 3, 9, 7, 1, 8, 5, 4, 2]
[7, 4, 5, 2, 9, 6, 8, 3, 1]
Step Count: 23

[MRV_DISABLED] Puzzle 4
Solution:
[9, 2, 3, 8, 7, 6, 5, 4, 1]
[6, 5, 8, 3, 1, 4, 7, 9, 2]
[4,

In [9]:
MRV_ENABLED = True
step_counts_mrv_enabled = {}
for p_idx in range(1, 10):
    original_puzzle = globals()[f"puzzle_{p_idx}"]
    puzzle_copy = copy.deepcopy(original_puzzle)
    s = state(input_board=puzzle_copy)
    print(f"\n[MRV_ENABLED] Puzzle {p_idx}")
    solved, final_steps = solve_sudoku(s)
    if solved:
        print("Solution:")
        for row_data in s.board:
            print(row_data)
        step_counts_mrv_enabled[p_idx] = final_steps
        print("Step Count:", final_steps)
    else:
        print("No solution found.")
        step_counts_mrv_enabled[p_idx] = None


[MRV_ENABLED] Puzzle 1
Solution:
[8, 2, 4, 7, 9, 5, 1, 6, 3]
[3, 5, 1, 2, 6, 4, 8, 7, 9]
[7, 9, 6, 8, 1, 3, 5, 4, 2]
[5, 7, 8, 4, 2, 1, 9, 3, 6]
[9, 6, 3, 5, 7, 8, 2, 1, 4]
[4, 1, 2, 6, 3, 9, 7, 8, 5]
[1, 4, 9, 3, 5, 7, 6, 2, 8]
[6, 3, 7, 9, 8, 2, 4, 5, 1]
[2, 8, 5, 1, 4, 6, 3, 9, 7]
Step Count: 24

[MRV_ENABLED] Puzzle 2
Solution:
[1, 9, 3, 7, 2, 8, 6, 5, 4]
[5, 4, 6, 3, 1, 9, 8, 2, 7]
[7, 2, 8, 5, 4, 6, 9, 3, 1]
[8, 7, 4, 2, 3, 5, 1, 9, 6]
[2, 6, 5, 8, 9, 1, 7, 4, 3]
[9, 3, 1, 6, 7, 4, 5, 8, 2]
[4, 8, 9, 1, 6, 2, 3, 7, 5]
[3, 1, 2, 9, 5, 7, 4, 6, 8]
[6, 5, 7, 4, 8, 3, 2, 1, 9]
Step Count: 24

[MRV_ENABLED] Puzzle 3
Solution:
[5, 1, 7, 8, 4, 3, 2, 9, 6]
[9, 6, 4, 5, 7, 2, 1, 8, 3]
[3, 2, 8, 1, 6, 9, 4, 5, 7]
[8, 7, 2, 9, 3, 5, 6, 1, 4]
[4, 5, 3, 6, 2, 1, 9, 7, 8]
[1, 9, 6, 4, 8, 7, 3, 2, 5]
[2, 8, 1, 3, 5, 4, 7, 6, 9]
[6, 3, 9, 7, 1, 8, 5, 4, 2]
[7, 4, 5, 2, 9, 6, 8, 3, 1]
Step Count: 23

[MRV_ENABLED] Puzzle 4
Solution:
[9, 2, 3, 8, 7, 6, 5, 4, 1]
[6, 5, 8, 3, 1, 4, 7, 9, 2]
[4, 1, 

In [10]:
print("\n=== Step Count Summary ===")
print("MRV Disabled Steps:", step_counts_mrv_disabled)
print("MRV Enabled Steps:", step_counts_mrv_enabled)


=== Step Count Summary ===
MRV Disabled Steps: {1: 24, 2: 24, 3: 23, 4: 43, 5: 42, 6: 43, 7: 47, 8: 48, 9: 48}
MRV Enabled Steps: {1: 24, 2: 24, 3: 23, 4: 43, 5: 42, 6: 43, 7: 47, 8: 48, 9: 48}


In [11]:
#Q-Learning Functions

class action:
    def __init__(self, row, col, val):
        self.row = row
        self.col = col
        self.val = val

class state:
    def __init__(self, input_board=None):
        if input_board is not None:
            self.board = np.array(input_board, dtype=int)
        else:
            self.board = np.zeros((9,9), dtype=int)
        self.row_candidates = [[True]*9 for _ in range(9)]
        self.col_candidates = [[True]*9 for _ in range(9)]
        self.box_candidates = [[True]*9 for _ in range(9)]
        self.candidate_init()

    def candidate_init(self):
        for r in range(9):
            for c in range(9):
                val = self.board[r][c]
                if val != 0:
                    self.number_select(r, c, val, True)

    def box_i(self, row, col):
        return (row // 3)*3 + (col // 3)

    def number_select(self, row, col, val, initialize=False):
        self.board[row][col] = val
        i = val - 1
        self.row_candidates[row][i] = False
        self.col_candidates[col][i] = False
        box_i = self.box_i(row, col)
        self.box_candidates[box_i][i] = False

    def number_correction(self, row, col, val):
        self.board[row][col] = 0
        i = val - 1
        self.row_candidates[row][i] = True
        self.col_candidates[col][i] = True
        box_i = self.box_i(row, col)
        self.box_candidates[box_i][i] = True

    def constrain_check(self, act):
        if self.board[act.row][act.col] != 0:
            return False
        i = act.val - 1
        box_i = self.box_i(act.row, act.col)
        return (self.row_candidates[act.row][i] and 
                self.col_candidates[act.col][i] and 
                self.box_candidates[box_i][i])

    def apply_action(self, act):
        self.number_select(act.row, act.col, act.val)

    def revert_action(self, act):
        self.number_correction(act.row, act.col, act.val)

    def find_possible_values(self, row, col):
        if self.board[row][col] != 0:
            return []
        possible_values_list = []
        for val in range(1, 10):
            i = val - 1
            box_i = self.box_i(row, col)
            if (self.row_candidates[row][i] and
                self.col_candidates[col][i] and
                self.box_candidates[box_i][i]):
                possible_values_list.append(val)
        return possible_values_list

    def is_solved(self):
        return np.all(self.board != 0)

def get_possible_actions(s):
    acts = []
    for r in range(9):
        for c in range(9):
            if s.board[r][c] == 0:
                candidates = s.find_possible_values(r, c)
                for v in candidates:
                    acts.append(action(r, c, v))
    return acts

def step(s, act):
    if s.constrain_check(act):
        s.apply_action(act)
        if s.is_solved():
            return s, 50.0, True
        else:
            return s, 0.1, False
    else:
        return s, 0.0, True

def encode_state(s):
    return tuple(s.board.flatten())

Q = {}
alpha = 0.1
gamma = 0.95
epsilon = 1.0
epsilon_decay = 0.995
epsilon_min = 0.01

def get_Q(state_key, act_key):
    return Q.get((state_key, act_key), 0.0)

def update_Q(old_s, a, reward, new_s, done):
    old_sk = encode_state(old_s)
    ak = (a.row,a.col,a.val)
    old_q = get_Q(old_sk, ak)
    if done:
        target = reward
    else:
        new_acts = get_possible_actions(new_s)
        if not new_acts:
            target = reward
        else:
            new_sk = encode_state(new_s)
            next_qs = [get_Q(new_sk,(na.row,na.col,na.val)) for na in new_acts]
            target = reward + gamma*max(next_qs)
    new_q = old_q + alpha*(target - old_q)
    Q[(old_sk, ak)] = new_q

def get_mrv_cell(s):
    min_candidates = 10
    candidates_cells = []
    for r in range(9):
        for c in range(9):
            if s.board[r][c] == 0:
                possible_values = s.find_possible_values(r, c)
                num_candidates = len(possible_values)
                if num_candidates > 0 and num_candidates < min_candidates:
                    min_candidates = num_candidates
                    candidates_cells = [(r, c)]
                elif num_candidates == min_candidates:
                    candidates_cells.append((r, c))
    if candidates_cells:
        return random.choice(candidates_cells)
    else:
        return None

def choose_action(s):
    global epsilon
    acts = get_possible_actions(s)
    if not acts:
        return None

    if MRV_ENABLED:
        cell = get_mrv_cell(s)
        if cell is not None:
            acts = [a for a in acts if a.row == cell[0] and a.col == cell[1]]

    if random.random() < epsilon:
        return random.choice(acts)
    else:
        sk = encode_state(s)
        q_vals = [(get_Q(sk,(a.row,a.col,a.val)), a) for a in acts]
        max_q = max(q_vals, key=lambda x:x[0])[0]
        max_actions = [a for q,a in q_vals if q == max_q]
        return random.choice(max_actions)

def solve_with_Q(s, Q):
    step_count = 0
    max_steps = 10000
    while not s.is_solved() and step_count < max_steps:
        acts = get_possible_actions(s)
        if not acts:
            break
        sk = encode_state(s)
        q_vals = []
        for a in acts:
            q_val = Q.get((sk, (a.row,a.col,a.val)), 0.0)
            q_vals.append((q_val, a))
        max_q = max(q_vals, key=lambda x:x[0])[0]
        best_actions = [a for q,a in q_vals if q == max_q]
        chosen_action = best_actions[0]
        if s.constrain_check(chosen_action):
            s.apply_action(chosen_action)
        else:
            break
        step_count += 1

    return s.is_solved(), s, step_count

In [14]:
#Learning Q-tables
import numpy as np
import random
puzzles = [puzzle_1, puzzle_2, puzzle_3, puzzle_4, puzzle_5, puzzle_6, puzzle_7, puzzle_8, puzzle_9]

MRV_ENABLED = False
episodes_per_puzzle = 10
max_steps = 200

q_learning_results_mrv_disabled = {}  # {퍼즐번호: (해결여부, 스텝수)}

for p_idx, puzzle_arr in enumerate(puzzles):
    puzzle_success_count = 0
    puzzle_fail_count = 0
    puzzle_cumulative_step_count = 0
    for ep in range(1, episodes_per_puzzle+1):
        s = state(input_board=puzzle_arr.copy())
        done = False
        step_count = 0
        while not done and step_count < max_steps:
            old_s = state(input_board=s.board.copy())
            a = choose_action(s)
            if a is None:
                r = 0.0
                done = True
                update_Q(old_s, action(0,0,1), r, old_s, done)
                break
            s, r, done = step(s, a)
            new_s = state(input_board=s.board.copy())
            update_Q(old_s, a, r, new_s, done)
            step_count += 1
            puzzle_cumulative_step_count += 1
        if s.is_solved():
            puzzle_success_count += 1
        else:
            puzzle_fail_count += 1
            fs = state(input_board=s.board.copy())
            update_Q(fs, action(0,0,1), -20.0, fs, True)
        if epsilon > epsilon_min:
            epsilon *= epsilon_decay
    print(f"[MRV_DISABLED] Puzzle {p_idx+1} Result: Success={puzzle_success_count}, Fail={puzzle_fail_count}, Steps={puzzle_cumulative_step_count}")
    # 테스트 실행
    test_s = state(input_board=puzzle_arr.copy())
    solved, final_state, steps = solve_with_Q(test_s, Q)
    q_learning_results_mrv_disabled[p_idx+1] = (solved, steps)

puzzles = [puzzle_1, puzzle_2, puzzle_3, puzzle_4, puzzle_5, puzzle_6, puzzle_7, puzzle_8, puzzle_9]

MRV_ENABLED = True
episodes_per_puzzle = 10
max_steps = 200

q_learning_results_mrv_enabled = {}  # {퍼즐번호: (해결여부, 스텝수)}

for p_idx, puzzle_arr in enumerate(puzzles):
    puzzle_success_count = 0
    puzzle_fail_count = 0
    puzzle_cumulative_step_count = 0
    for ep in range(1, episodes_per_puzzle+1):
        s = state(input_board=puzzle_arr.copy())
        done = False
        step_count = 0
        while not done and step_count < max_steps:
            old_s = state(input_board=s.board.copy())
            a = choose_action(s)
            if a is None:
                r = 0.0
                done = True
                update_Q(old_s, action(0,0,1), r, old_s, done)
                break
            s, r, done = step(s, a)
            new_s = state(input_board=s.board.copy())
            update_Q(old_s, a, r, new_s, done)
            step_count += 1
            puzzle_cumulative_step_count += 1
        if s.is_solved():
            puzzle_success_count += 1
        else:
            puzzle_fail_count += 1
            fs = state(input_board=s.board.copy())
            update_Q(fs, action(0,0,1), -20.0, fs, True)
        if epsilon > epsilon_min:
            epsilon *= epsilon_decay
    print(f"[MRV_ENABLED] Puzzle {p_idx+1} Result: Success={puzzle_success_count}, Fail={puzzle_fail_count}, Steps={puzzle_cumulative_step_count}")
    # 테스트 실행
    test_s = state(input_board=puzzle_arr.copy())
    solved, final_state, steps = solve_with_Q(test_s, Q)
    q_learning_results_mrv_enabled[p_idx+1] = (solved, steps)

epsilon = 0.0

[MRV_DISABLED] Puzzle 1 Result: Success=0, Fail=10, Steps=190
[MRV_DISABLED] Puzzle 2 Result: Success=0, Fail=10, Steps=175
[MRV_DISABLED] Puzzle 3 Result: Success=2, Fail=8, Steps=206
[MRV_DISABLED] Puzzle 4 Result: Success=0, Fail=10, Steps=302
[MRV_DISABLED] Puzzle 5 Result: Success=0, Fail=10, Steps=320
[MRV_DISABLED] Puzzle 6 Result: Success=0, Fail=10, Steps=307
[MRV_DISABLED] Puzzle 7 Result: Success=0, Fail=10, Steps=339
[MRV_DISABLED] Puzzle 8 Result: Success=0, Fail=10, Steps=346
[MRV_DISABLED] Puzzle 9 Result: Success=0, Fail=10, Steps=350
[MRV_ENABLED] Puzzle 1 Result: Success=10, Fail=0, Steps=240
[MRV_ENABLED] Puzzle 2 Result: Success=10, Fail=0, Steps=240
[MRV_ENABLED] Puzzle 3 Result: Success=10, Fail=0, Steps=230
[MRV_ENABLED] Puzzle 4 Result: Success=10, Fail=0, Steps=430
[MRV_ENABLED] Puzzle 5 Result: Success=1, Fail=9, Steps=395
[MRV_ENABLED] Puzzle 6 Result: Success=10, Fail=0, Steps=430
[MRV_ENABLED] Puzzle 7 Result: Success=10, Fail=0, Steps=470
[MRV_ENABLED] Puz

In [17]:
# MRV_ENABLED = False인 경우 결과 저장
MRV_ENABLED = False
mrv_disabled_results = {}

for i in range(1, 10):
    puzzle = globals()[f"puzzle_{i}"]
    s = state(input_board=puzzle.copy())
    solved, final_state, steps = solve_with_Q(s, Q)
    print(f"[MRV_DISABLED] Puzzle {i}")
    print("Solved:", solved)
    print("Steps:", steps)
    print(final_state.board)
    print("-"*40)
    # solved 여부에 따라 문자열 결정
    status_str = "solved" if solved else "unsolved"
    mrv_disabled_results[i] = (steps, status_str)




# MRV_ENABLED = True인 경우 결과 저장
MRV_ENABLED = True
mrv_enabled_results = {}

for i in range(1, 10):
    puzzle = globals()[f"puzzle_{i}"]
    s = state(input_board=puzzle.copy())
    solved, final_state, steps = solve_with_Q(s, Q)
    print(f"[MRV_ENABLED] Puzzle {i}")
    print("Solved:", solved)
    print("Steps:", steps)
    print(final_state.board)
    print("-"*40)
    status_str = "solved" if solved else "unsolved"
    mrv_enabled_results[i] = (steps, status_str)




[MRV_DISABLED] Puzzle 1
Solved: False
Steps: 19
[[8 2 4 7 9 5 1 6 3]
 [3 5 1 2 6 4 8 7 9]
 [7 9 6 8 1 3 5 4 2]
 [5 7 8 4 2 1 9 3 6]
 [9 6 0 5 3 8 2 1 4]
 [4 3 2 6 0 9 7 8 5]
 [0 4 9 3 5 7 6 2 8]
 [1 0 7 9 8 2 4 5 0]
 [2 8 5 1 4 6 3 9 7]]
----------------------------------------
[MRV_DISABLED] Puzzle 2
Solved: True
Steps: 24
[[1 9 3 7 2 8 6 5 4]
 [5 4 6 3 1 9 8 2 7]
 [7 2 8 5 4 6 9 3 1]
 [8 7 4 2 3 5 1 9 6]
 [2 6 5 8 9 1 7 4 3]
 [9 3 1 6 7 4 5 8 2]
 [4 8 9 1 6 2 3 7 5]
 [3 1 2 9 5 7 4 6 8]
 [6 5 7 4 8 3 2 1 9]]
----------------------------------------
[MRV_DISABLED] Puzzle 3
Solved: True
Steps: 23
[[5 1 7 8 4 3 2 9 6]
 [9 6 4 5 7 2 1 8 3]
 [3 2 8 1 6 9 4 5 7]
 [8 7 2 9 3 5 6 1 4]
 [4 5 3 6 2 1 9 7 8]
 [1 9 6 4 8 7 3 2 5]
 [2 8 1 3 5 4 7 6 9]
 [6 3 9 7 1 8 5 4 2]
 [7 4 5 2 9 6 8 3 1]]
----------------------------------------
[MRV_DISABLED] Puzzle 4
Solved: True
Steps: 43
[[9 2 3 8 7 6 5 4 1]
 [6 5 8 3 1 4 7 9 2]
 [4 1 7 9 2 5 6 8 3]
 [3 7 2 1 5 8 9 6 4]
 [8 9 4 6 3 7 1 2 5]
 [5 6 1 2 4 9

In [18]:
print("\n=== Step Count Summary ===")
print("MRV Disabled Steps:", step_counts_mrv_disabled)
print("MRV Enabled Steps:", step_counts_mrv_enabled)
print("\n=== Step Count Summary ===")
print("MRV Disabled Steps:", mrv_disabled_results)
print("MRV Enabled Steps:", mrv_enabled_results)


=== Step Count Summary ===
MRV Disabled Steps: {1: 24, 2: 24, 3: 23, 4: 43, 5: 42, 6: 43, 7: 47, 8: 48, 9: 48}
MRV Enabled Steps: {1: 24, 2: 24, 3: 23, 4: 43, 5: 42, 6: 43, 7: 47, 8: 48, 9: 48}

=== Step Count Summary ===
MRV Disabled Steps: {1: (19, 'unsolved'), 2: (24, 'solved'), 3: (23, 'solved'), 4: (43, 'solved'), 5: (38, 'unsolved'), 6: (43, 'solved'), 7: (47, 'solved'), 8: (48, 'solved'), 9: (48, 'solved')}
MRV Enabled Steps: {1: (19, 'unsolved'), 2: (24, 'solved'), 3: (23, 'solved'), 4: (43, 'solved'), 5: (38, 'unsolved'), 6: (43, 'solved'), 7: (47, 'solved'), 8: (48, 'solved'), 9: (48, 'solved')}


In [ ]:
#The 